# Generated by Django 4.0.3 on 2022-05-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
