# Generated by Django 4.0.3 on 2022-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('bids', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('img_url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
