# Generated by Django 4.0.3 on 2022-05-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_owner_auctions_owner_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auctions',
            new_name='listings',
        ),
    ]
