# Generated by Django 4.0.3 on 2022-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
